<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="6.59s"
		durationms="6588"
		type="root"
		rid="285a7e86eae88655"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="Ezequiel Rodas"
		rxversion="9.3.4.0"
		host="DESKTOP-16RK4EQ"
		osversion="Windows 10 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="es-ES"
		dtnlanguage="es-ES"
		screenresolution="1366x768"
		timestamp="12/12/2022 17:37:28"
		timestampiso="2022-12-12T19:37:28"
		endtime="12/12/2022 17:37:58"
		timeoutfactor="1"
		runid=""
		sutversion="">
		<detail>
			Ranorex Testscript
		</detail>
		<item
			timeRelativeToTestSuiteStartTime="00:06.575"
			timeRelativeToTestModuleStartTime="00:06.575"
			timeWallClock="17:37:34"
			time="00:06.575"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
		<item
			timeRelativeToTestSuiteStartTime="00:09.867"
			timeRelativeToTestModuleStartTime="00:09.867"
			timeWallClock="17:37:37"
			time="00:09.867"
			level="Failure"
			category="Module"
			errimg="images_FiltroPo_32e79dcd\FiltroPo_32e79dcd_fd7f9160_trace.jpg"
			errthumb="images_FiltroPo_32e79dcd\FiltroPo_32e79dcd_fd7f9160_trace_thumb.jpg">
			<message>
				Subproceso anulado.
			</message>
			<metainfo
				stacktrace="   en Ranorex.Keyboard.set_AbortKey(Keys value)
   en Ranorex.Core.Testing.TestModuleRunner.RunStandalone(ITestModule module, String reportFilename, Boolean generateReport, String standaloneModuleName, CaseInsensitiveString guid)"
				loglvl="Failure">
			</metainfo>
		</item>
	</activity>
</report>
